name: ci
on: [pull_request, push]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: canary
          
      - name: check lint
        run: deno lint
       
      - name: check bundle
        run: deno task test:bundle
        
      - name: run tests
        run: deno task test
