name: ci
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: run tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: canary
          
      - name: check lint
        if: matrix.os == 'ubuntu-latest'
        run: deno lint --json ./
       
      - name: check bundle
        run: deno task test:bundle
        
      - name: run tests
        run: deno task test
