name: Tests
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    env:
      DENO_DIR: cache_dir

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: canary
          
      - name: Cache dependencies 
        uses: actions/cache@v3.0.10
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_KEY }}

      - name: check lint
        run: deno lint
        
      - name: check bundle
        run: deno task test:bundle
        
      - name: run tests
        run: deno task test
